version: '3'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/backend
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=contest_platform_database
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: contest_platform_database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
