FROM python:3.12

WORKDIR /backend

COPY ./backend .

RUN pip install pipx && \
    pipx install poetry && \
    export PATH=$PATH:/root/.local/bin && \
    poetry install

ENV PATH=/root/.local/bin:$PATH

EXPOSE 8000

# migracje bazy danych
CMD ["poetry", "run", "python", "manage.py", "makemigrations", "&&", "poetry", "run", "python", "manage.py", "migrate", "&&", "poetry", "run", "python", "manage.py", "runserver", "0.0.0.0:8000"]

