FROM python:3.12

WORKDIR /backend

COPY ./backend .
COPY ./backend/entrypoint.sh /backend
RUN chmod +x /backend/entrypoint.sh

RUN pip install pipx && \
    pipx install poetry && \
    export PATH=$PATH:/root/.local/bin && \
    poetry install

ENV PATH=/root/.local/bin:$PATH

COPY ./backend .

CMD ["poetry", "run", "python", "manage.py", "rundramatiq"]