# Generated by Django 5.0 on 2024-01-02 12:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=10)),
                ('postal_code', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='contest',
            name='date_start',
            field=models.DateField(default=datetime.date(2023, 3, 15)),
        ),
        migrations.CreateModel(
            name='AssessmentCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('max_rating', models.IntegerField()),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest_platform.contest')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestant_name', models.CharField(max_length=20)),
                ('parent_name', models.CharField(max_length=20, null=True)),
                ('contestant_surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('entry_title', models.CharField(max_length=100)),
                ('entry_file', models.BinaryField(null=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contest_platform.address')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest_platform.contest')),
            ],
        ),
    ]
