# Generated by Django 5.0 on 2023-12-11 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='date_end',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='contest',
            name='date_start',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='contest',
            name='individual',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='poster_img',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='rules_pdf',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
