# Generated by Django 5.0 on 2024-01-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_platform', '0002_address_alter_contest_date_start_assessmentcriterion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_jury',
            field=models.BooleanField(default=False),
        ),
    ]
