# Generated by Django 5.0 on 2023-12-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest_platform", "0002_contest_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contest",
            name="title",
            field=models.CharField(default="", max_length=200),
        ),
    ]
