# Generated by Django 5.0 on 2023-12-26 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest_platform', '0002_contest_date_end_contest_date_start_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
