# Generated by Django 5.0 on 2024-01-11 23:04

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_platform', '0003_user_is_jury'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='contestant_name',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='contestant_surname',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='parent_name',
        ),
        migrations.AddField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contest',
            name='date_start',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='contest',
            name='poster_img',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='rules_pdf',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_file',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='contestants',
            field=models.ManyToManyField(to='contest_platform.person'),
        ),
    ]
