# Generated by Django 5.0 on 2024-01-12 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest_platform', '0004_person_remove_entry_contestant_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssessmentCriterion',
            new_name='GradeCriterion',
        ),
    ]
